# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 17:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180704_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailveritycode',
            name='send_date',
            field=models.DateField(default=datetime.date(2018, 7, 4), verbose_name='\u53d1\u9001\u6708\u4efd'),
        ),
        migrations.AlterField(
            model_name='emailveritycode',
            name='send_type',
            field=models.CharField(choices=[('register', '\u6ce8\u518c'), ('forget', '\u627e\u56de\u5bc6\u7801')], max_length=20, verbose_name='\u7c7b\u578b'),
        ),
    ]
