# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180704_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailveritycode',
            name='send_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='\u53d1\u9001\u6708\u4efd'),
        ),
    ]
