# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180704_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailveritycode',
            name='send_date',
        ),
    ]
