# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-26 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_emailveritycode_send_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nickname',
            new_name='name',
        ),
    ]
