# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-31 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180726_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='useremail',
            field=models.EmailField(default='', max_length=20, verbose_name='\u7528\u6237\u90ae\u7bb1'),
        ),
    ]
