# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-31 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_useremail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='useremail',
        ),
    ]
