# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-20 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180717_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='learn_time',
            field=models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u65f6\u957f'),
        ),
    ]
