# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-27 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_org'),
    ]

    operations = [

    ]
