# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-27 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='need_know',
            field=models.CharField(default='', max_length=100, verbose_name='\u8bfe\u7a0b\u9700\u77e5'),
        ),
        migrations.AddField(
            model_name='course',
            name='to_learn',
            field=models.CharField(default='', max_length=100, verbose_name='\u8bb2\u5e08\u63d0\u793a'),
        ),
    ]
