# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-23 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20180719_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userask',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='\u624b\u673a\u53f7\u7801'),
        ),
    ]
